baseurl = "http://goserv.it"
title = "goserv - A lightweight toolkit for web applications in Go"
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
languagecode = "en-us"
pygmentsstyle = "tango"
theme = "light"

[params]
    Author = "Marcel Gotsch"
    Name = "goserv"
    Intro = "<strong>goserv</strong> is a fully compatible toolkit for <i>Go's</i> <strong>net/http</strong> package, making the creation of powerful and complex web applications even easier."
    Description = "A lightweight toolkit for web applications in Go"
    GithubUser = "gotschmarcel"
    GithubLink = "//github.com/gotschmarcel/goserv"
    Twitter = "gotschmarcel"
    Mail = "hello@goserv.it"
    Keywords = ["goserv", "go", "golang", "framework"]

# Menu Structure
[[menu.main]]
    name = "News"
    weight = -200
    identifier = "news"
    url = "/news"

[[menu.main]]
    name = "Getting Started"
    weight = -100
    identifier = "getting_started"

[[menu.main]]
    name = "Documentation"
    weight = -90
    identifier = "documentation"

[[menu.main]]
    parent = "documentation"
    name = "API Reference"
    weight = -110
    url = "https://godoc.org/github.com/gotschmarcel/goserv"
